import type { Lang } from './i18n';
const copy = {
  controls: ['Mission controls', 'Điều khiển bài tập'],
  scene: ['Environment', 'Môi trường'],
  reset: ['Reset exercise', 'Đặt lại bài tập'],
  play: ['Run', 'Chạy'],
  pause: ['Pause', 'Tạm dừng'],
  next: ['Advance one step', 'Tiến một bước'],
  previous: ['Previous frame', 'Khung trước'],
  findings: ['Situation brief', 'Tóm tắt tình huống'],
  status: ['Status', 'Trạng thái'],
  selected: ['Selected system', 'Hệ thống đã chọn'],
  healthy: ['Ready', 'Sẵn sàng'],
  compromised: ['Compromised', 'Bị xâm nhập'],
  isolated: ['Isolated', 'Đã cô lập'],
  encrypted: ['Encrypted', 'Đã mã hóa'],
  restored: ['Restored', 'Đã khôi phục'],
  reachable: ['Reachable', 'Có thể tiếp cận'],
  blocked: ['Blocked', 'Bị chặn'],
  allowed: ['Allowed', 'Được phép'],
  waiting: ['Waiting', 'Đang chờ'],
  protected: ['Protected', 'Được bảo vệ'],
  edge: ['Edge gateway', 'Cổng mạng'],
  identity: ['Identity / IAM-04', 'Danh tính / IAM-04'],
  ws17: ['Workstation / WS-17', 'Máy trạm / WS-17'],
  app: ['Application / APP-02', 'Ứng dụng / APP-02'],
  db: ['Database / DB-01', 'Cơ sở dữ liệu / DB-01'],
  backup: ['Backup / BK-01', 'Sao lưu / BK-01'],
  storage: ['Object storage', 'Kho đối tượng'],
  admin: ['Admin role', 'Vai trò quản trị'],
  analyst: ['Analyst role', 'Vai trò phân tích'],
  public: ['Public entry', 'Điểm vào công khai'],
  orbit: [
    'Drag to orbit; pinch to zoom. Select a system or use the system buttons.',
    'Kéo để xoay; chụm để thu phóng. Chọn hệ thống hoặc dùng các nút bên dưới.',
  ],
  camera: ['Camera controls', 'Điều khiển góc nhìn'],
  left: ['Rotate left', 'Xoay trái'],
  right: ['Rotate right', 'Xoay phải'],
  zoomIn: ['Zoom in', 'Phóng to'],
  zoomOut: ['Zoom out', 'Thu nhỏ'],
  home: ['Reset camera', 'Đặt lại góc nhìn'],
  fallback: [
    '3D is unavailable here. The interactive diagram remains usable.',
    'Không có 3D trong trình duyệt này. Sơ đồ tương tác vẫn sử dụng được.',
  ],
  motion: ['Animate traffic', 'Chuyển động lưu lượng'],
  twinHint: [
    'Select an entry route, launch it, then interrupt the path with controls or terminal commands.',
    'Chọn đường vào, khởi chạy rồi ngắt đường truy cập bằng điều khiển hoặc lệnh terminal.',
  ],
  entry: ['Entry route', 'Đường vào'],
  password: ['Stolen password', 'Mật khẩu bị đánh cắp'],
  attachment: ['Malicious attachment', 'Tệp đính kèm độc hại'],
  launch: ['Launch scenario', 'Khởi chạy tình huống'],
  mfa: ['MFA', 'MFA'],
  edr: ['Endpoint isolation response', 'Ứng phó cô lập thiết bị'],
  segment: ['Data-tier segmentation', 'Phân đoạn tầng dữ liệu'],
  backups: ['Isolated recovery copy', 'Bản khôi phục tách biệt'],
  defenseNote: [
    'Controls interrupt specific paths in this exercise. They do not establish real-world protection guarantees.',
    'Các biện pháp ngắt những đường cụ thể trong bài tập, không đảm bảo khả năng bảo vệ ngoài thực tế.',
  ],
  attackStopped: [
    'Entry interrupted. Downstream systems have not been reached.',
    'Điểm vào bị ngắt. Các hệ thống phía sau chưa bị tiếp cận.',
  ],
  dataStopped: [
    'The application is exposed, but the data-tier boundary stops this path.',
    'Ứng dụng bị phơi nhiễm nhưng ranh giới tầng dữ liệu chặn đường này.',
  ],
  attackOpen: [
    'The entry path reaches the application and database. Interrupt access before the next stage.',
    'Đường vào tiếp cận ứng dụng và cơ sở dữ liệu. Ngắt truy cập trước giai đoạn tiếp theo.',
  ],
  idle: [
    'The environment is ready. Start an exercise or inspect a system.',
    'Môi trường sẵn sàng. Bắt đầu bài tập hoặc kiểm tra hệ thống.',
  ],
  legitimate: ['Legitimate requests / second', 'Yêu cầu hợp lệ / giây'],
  attack: ['Attack requests / second', 'Yêu cầu tấn công / giây'],
  capacity: ['Origin capacity / second', 'Công suất máy chủ gốc / giây'],
  rate: ['Admission limit / second', 'Giới hạn tiếp nhận / giây'],
  cache: ['Cache hit rate (%)', 'Tỷ lệ trúng bộ nhớ đệm (%)'],
  filter: ['Traffic filtering', 'Lọc lưu lượng'],
  queue: ['Queued requests', 'Yêu cầu trong hàng đợi'],
  latency: ['Estimated queue delay', 'Độ trễ hàng đợi ước tính'],
  served: ['Immediate legitimate throughput / second', 'Yêu cầu hợp lệ được phục vụ ngay / giây'],
  rejected: ['Legitimate requests rejected / second', 'Yêu cầu hợp lệ bị từ chối / giây'],
  dropped: ['Attack requests filtered / second', 'Yêu cầu tấn công bị lọc / giây'],
  elapsed: ['Exercise time', 'Thời gian bài tập'],
  ddosHint: [
    'Run the exercise to accumulate queues. Lower admission limits can also reject legitimate visitors; caching reduces load only for legitimate cacheable reads.',
    'Chạy bài tập để quan sát hàng đợi. Giới hạn thấp có thể từ chối khách hợp lệ; bộ nhớ đệm chỉ giảm tải cho yêu cầu đọc hợp lệ có thể lưu.',
  ],
  overloaded: [
    'Incoming origin work exceeds capacity. The queue grows with each second.',
    'Lượng xử lý đến máy chủ gốc vượt công suất. Hàng đợi tăng mỗi giây.',
  ],
  balanced: [
    'Origin demand fits available capacity. Any existing queue drains over time.',
    'Nhu cầu phù hợp công suất máy chủ gốc. Hàng đợi hiện có giảm dần.',
  ],
  tradeoff: [
    'Admission limits affect both traffic classes. Check rejected legitimate requests before lowering the limit further.',
    'Giới hạn tiếp nhận tác động đến cả hai loại lưu lượng. Kiểm tra số yêu cầu hợp lệ bị từ chối trước khi hạ thêm.',
  ],
  terminal: ['Response terminal', 'Terminal ứng phó'],
  command: ['Command', 'Lệnh'],
  execute: ['Execute', 'Thực thi'],
  terminalIntro: [
    'Type help for commands. Arrow keys recall history; Tab completes a known command. Commands control only this fictional environment.',
    'Nhập help để xem lệnh. Phím mũi tên gọi lịch sử; Tab hoàn thành lệnh đã biết. Lệnh chỉ điều khiển môi trường hư cấu này.',
  ],
  unknown: ['Unknown command. Type help.', 'Lệnh không hợp lệ. Nhập help.'],
  changed: ['Environment updated.', 'Đã cập nhật môi trường.'],
  cleared: ['Terminal cleared.', 'Đã xóa terminal.'],
  alertLogin: ['IAM-04: suspicious administrator session', 'IAM-04: phiên quản trị đáng ngờ'],
  alertHost: [
    'WS-17: unexpected script and outbound connection',
    'WS-17: mã lệnh và kết nối ra ngoài bất thường',
  ],
  terminalEvidence: [
    '09:12 unfamiliar sign-in → 09:14 privileged session → 09:17 application access.',
    '09:12 đăng nhập lạ → 09:14 phiên đặc quyền → 09:17 truy cập ứng dụng.',
  ],
  ransomwareHint: [
    'Each step is one propagation wave. Isolate a node to stop traffic through it. A clean, isolated backup is needed to restore affected nodes.',
    'Mỗi bước là một đợt lây lan. Cô lập nút để ngắt lưu lượng qua nó. Cần bản sao lưu sạch và tách biệt để khôi phục nút bị ảnh hưởng.',
  ],
  isolate: ['Isolate selected system', 'Cô lập hệ thống đã chọn'],
  restore: ['Restore selected system', 'Khôi phục hệ thống đã chọn'],
  wave: ['Propagation wave', 'Đợt lây lan'],
  affected: ['Affected systems', 'Hệ thống bị ảnh hưởng'],
  recovery: ['Recovery source', 'Nguồn khôi phục'],
  cleanBackup: ['Clean isolated backup available', 'Có bản sao lưu sạch tách biệt'],
  lostBackup: ['No clean recovery source', 'Không còn nguồn khôi phục sạch'],
  restoreNeed: [
    'Isolate an encrypted system and preserve a clean backup before restoring it.',
    'Cô lập hệ thống bị mã hóa và giữ bản sao lưu sạch trước khi khôi phục.',
  ],
  restoreDone: [
    'The selected system is restored and remains isolated pending validation.',
    'Hệ thống đã khôi phục và tiếp tục được cô lập để chờ xác minh.',
  ],
  raceDone: [
    'Propagation has stopped. Review affected systems and the remaining recovery source.',
    'Đã ngừng lây lan. Kiểm tra hệ thống bị ảnh hưởng và nguồn khôi phục còn lại.',
  ],
  packets: ['Captured packets', 'Gói tin đã ghi nhận'],
  packetHint: [
    'Select a moving packet or a packet button, open its layers, and change the inspection rules.',
    'Chọn gói tin chuyển động hoặc nút gói tin, mở các lớp và thay đổi quy tắc kiểm tra.',
  ],
  normal: ['Authorized HTTPS read', 'Đọc HTTPS được cấp phép'],
  injection: ['Suspicious write pattern', 'Mẫu ghi đáng ngờ'],
  unapproved: ['Unapproved source', 'Nguồn chưa được phép'],
  protocol: ['Protocol layers', 'Các lớp giao thức'],
  ethernet: ['Link layer', 'Lớp liên kết'],
  network: ['Network layer', 'Lớp mạng'],
  transport: ['Transport layer', 'Lớp truyền tải'],
  application: ['Application layer', 'Lớp ứng dụng'],
  sourceRule: ['Require approved source', 'Yêu cầu nguồn được phép'],
  portRule: ['Allow HTTPS port only', 'Chỉ cho phép cổng HTTPS'],
  inspectRule: ['Inspect application pattern', 'Kiểm tra mẫu ứng dụng'],
  packetAllow: [
    'No enabled rule rejects this packet. Passing inspection does not prove a request is safe.',
    'Không có quy tắc đang bật từ chối gói này. Qua kiểm tra không chứng minh yêu cầu an toàn.',
  ],
  sourceBlocked: ['Rejected by the source rule.', 'Bị từ chối bởi quy tắc nguồn.'],
  portBlocked: ['Rejected by the destination-port rule.', 'Bị từ chối bởi quy tắc cổng đích.'],
  patternBlocked: [
    'Rejected by the application-pattern rule.',
    'Bị từ chối bởi quy tắc mẫu ứng dụng.',
  ],
  role: ['User role', 'Vai trò người dùng'],
  employee: ['Employee', 'Nhân viên'],
  administrator: ['Administrator', 'Quản trị viên'],
  guest: ['Guest', 'Khách'],
  device: ['Device health', 'Tình trạng thiết bị'],
  managed: ['Managed and healthy', 'Được quản lý và an toàn'],
  unmanaged: ['Unmanaged', 'Chưa được quản lý'],
  location: ['Network context', 'Bối cảnh mạng'],
  trusted: ['Trusted network', 'Mạng tin cậy'],
  unfamiliar: ['Unfamiliar network', 'Mạng lạ'],
  resource: ['Requested resource', 'Tài nguyên yêu cầu'],
  docs: ['Team documents', 'Tài liệu nhóm'],
  console: ['Admin console', 'Bảng quản trị'],
  verified: ['Identity verified with MFA', 'Danh tính đã xác minh bằng MFA'],
  checkpoints: ['Identity|Device|Context|Resource', 'Danh tính|Thiết bị|Bối cảnh|Tài nguyên'],
  zeroHint: [
    'Change one input at a time. A denied checkpoint stops later evaluation; the resource policy distinguishes team access from administration.',
    'Thay đổi từng đầu vào. Chốt từ chối sẽ dừng đánh giá phía sau; chính sách phân biệt truy cập nhóm với quản trị.',
  ],
  identityDeny: [
    'Verify identity with MFA before granting access.',
    'Xác minh danh tính bằng MFA trước khi cấp quyền.',
  ],
  deviceDeny: [
    'This resource requires a managed, healthy device.',
    'Tài nguyên yêu cầu thiết bị được quản lý và an toàn.',
  ],
  contextDeny: [
    'This exercise requires a trusted network context.',
    'Bài tập yêu cầu bối cảnh mạng tin cậy.',
  ],
  resourceDeny: [
    'The selected role does not have permission for this resource.',
    'Vai trò đã chọn không có quyền đối với tài nguyên này.',
  ],
  accessAllow: [
    'Every checkpoint passes for this request. Re-evaluate when the context changes.',
    'Yêu cầu vượt qua tất cả chốt. Đánh giá lại khi bối cảnh thay đổi.',
  ],
  frame: ['Replay position', 'Vị trí phát lại'],
  viewpoint: ['Viewpoint', 'Góc nhìn'],
  defender: ['Analyst', 'Chuyên viên'],
  attacker: ['Intrusion path', 'Đường xâm nhập'],
  business: ['Service impact', 'Ảnh hưởng dịch vụ'],
  replayHint: [
    'Scrub or play the six recorded frames. Every panel follows the same clock; switching viewpoints changes the interpretation, not the event sequence.',
    'Di chuyển hoặc phát sáu khung ghi sẵn. Các bảng dùng cùng đồng hồ; đổi góc nhìn chỉ đổi diễn giải, không đổi sự kiện.',
  ],
  replayStages: [
    'Unfamiliar sign-in|Privileged session|Application reached|Data accessed|Access contained|Service recovered',
    'Đăng nhập lạ|Phiên đặc quyền|Tiếp cận ứng dụng|Truy cập dữ liệu|Cô lập truy cập|Khôi phục dịch vụ',
  ],
  replayLogs: [
    '09:12 IAM-04 sign-in from unfamiliar network|09:14 privileged session issued|09:17 APP-02 session opened|09:21 DB-01 archive read|09:28 session revoked; WS-17 isolated|10:06 DB-01 restored; credentials rotated',
    '09:12 IAM-04 đăng nhập từ mạng lạ|09:14 cấp phiên đặc quyền|09:17 mở phiên APP-02|09:21 đọc kho dữ liệu DB-01|09:28 thu hồi phiên; cô lập WS-17|10:06 khôi phục DB-01; đổi thông tin đăng nhập',
  ],
  analystNotes: [
    'Validate the sign-in against expected activity.|Inspect the new session and privilege scope.|Correlate application events with the session.|Scope affected records and preserve evidence.|Confirm revocation and isolation across systems.|Validate recovery before reconnecting services.',
    'Đối chiếu đăng nhập với hoạt động dự kiến.|Kiểm tra phiên mới và phạm vi đặc quyền.|Liên kết sự kiện ứng dụng với phiên.|Xác định dữ liệu bị ảnh hưởng và giữ bằng chứng.|Xác nhận thu hồi và cô lập trên các hệ thống.|Xác minh khôi phục trước khi kết nối lại dịch vụ.',
  ],
  attackerNotes: [
    'An unfamiliar source reaches identity.|The session provides privileged access.|Application access extends the path.|The path now reaches the data tier.|Revocation interrupts the entry path.|Rotated credentials close the old session.',
    'Nguồn lạ tiếp cận danh tính.|Phiên cung cấp quyền đặc biệt.|Ứng dụng mở rộng đường truy cập.|Đường truy cập tới tầng dữ liệu.|Thu hồi ngắt đường vào.|Đổi thông tin đăng nhập đóng phiên cũ.',
  ],
  businessNotes: [
    'Services remain available; suspicious activity begins.|Services remain available; access risk increases.|The application remains available but is exposed.|Data access needs impact assessment.|Affected access is interrupted for containment.|Services return after recovery validation.',
    'Dịch vụ vẫn sẵn sàng; bắt đầu hoạt động đáng ngờ.|Dịch vụ vẫn sẵn sàng; rủi ro truy cập tăng.|Ứng dụng vẫn sẵn sàng nhưng bị phơi nhiễm.|Cần đánh giá tác động truy cập dữ liệu.|Ngắt truy cập bị ảnh hưởng để cô lập.|Dịch vụ trở lại sau xác minh khôi phục.',
  ],
  log: ['Event log', 'Nhật ký sự kiện'],
  action: ['Analyst action', 'Thao tác chuyên viên'],
  principal: ['Compromised principal', 'Danh tính bị xâm nhập'],
  developer: ['Developer identity', 'Danh tính lập trình viên'],
  service: ['Service identity', 'Danh tính dịch vụ'],
  permissions: ['Permission edges', 'Các cạnh quyền truy cập'],
  assume: ['Developer → admin role', 'Lập trình viên → vai trò quản trị'],
  invoke: ['Developer → application', 'Lập trình viên → ứng dụng'],
  readStorage: ['Service → object storage', 'Dịch vụ → kho đối tượng'],
  adminDb: ['Admin role → database', 'Vai trò quản trị → cơ sở dữ liệu'],
  adminStorage: ['Admin role → object storage', 'Vai trò quản trị → kho đối tượng'],
  appDb: ['Application → database', 'Ứng dụng → cơ sở dữ liệu'],
  storageBackup: ['Object storage → backup', 'Kho đối tượng → sao lưu'],
  blastHint: [
    'Reachability follows the enabled, directed permission edges. Remove an edge to shrink access; a second route can keep a resource reachable.',
    'Khả năng tiếp cận theo cạnh quyền có hướng đang bật. Gỡ cạnh để thu hẹp truy cập; đường khác có thể vẫn tiếp cận tài nguyên.',
  ],
  blastCount: ['Reachable resources', 'Tài nguyên có thể tiếp cận'],
  blastNote: [
    'Highlighted resources are reachable through this permission graph. Other policies and vulnerabilities are outside this model.',
    'Tài nguyên được đánh dấu có thể tiếp cận qua đồ thị quyền này. Chính sách và lỗ hổng khác nằm ngoài mô hình.',
  ],
} satisfies Record<string, readonly [string, string]>;
export type RangeCopyKey = keyof typeof copy;
export type RangeCopy = Record<RangeCopyKey, string>;
export function rangeCopy(lang: Lang): RangeCopy {
  return Object.fromEntries(
    Object.entries(copy).map(([key, value]) => [key, value[lang === 'vi' ? 1 : 0]]),
  ) as RangeCopy;
}
